#!/usr/bin/env python
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import os.path
import subprocess

from rk import RK

rk = RK()
rk.authorize()

try:
    os.mkdir('gpx')
except OSError:
    pass

os.chdir('gpx')

for item in rk.get_fitness_items():
    if item['type'] != 'Cycling':
        continue
    # odds of being an integer number of minutes is low
    elif item['duration'] % 60 == 0:
        continue
