#!/usr/bin/env python
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json

from db import Session

Session.initialise()

session = Session.session

from orm import User, Track, NoResultFound
from rk import RK, NotModified


for user in session.query(User).all():
    print "Downloading for user '{}'...".format(user.user_id)

    rk = RK(token=user.token)

    for item in rk.get_fitness_items():
        if item['type'] != 'Cycling':
            continue

        track_id = item['uri']

        print "  {}...".format(track_id),

        try:
            track = Track.get_track(user, track_id)
            updated = track.updated
            print "existing,",
        except NoResultFound:
            print "new,",
            updated = None

        try:
            json = rk.get_fitness_item(item, if_modified_since=updated)
        except NotModified:
            print "not modified"
            continue

        print "downloaded"

        if json['equipment'] != 'None':
            continue

        Track.from_rk_json(json)
