#!/usr/bin/env python
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import os
import os.path

from orm import User, session
from rk import RK

try:
    os.mkdir('tracks')
except OSError:
    pass

for user in session.query(User).all():
    rk = RK(token=user.token)

    for item in rk.get_fitness_items():
        if item['type'] != 'Cycling':
            continue

        filename = os.path.join('tracks', item['uri'].split('/')[-1] + '.json')

        if os.path.exists(filename):
            continue

        with open(filename, 'w') as f:
            print "Downloading {}...".format(filename)
            resp = rk.get_fitness_item(item['uri'])
            json.dump(resp, f, indent=2)
